### ISSUE TITLE
MissingSchema in Process classifications when trying to create files for model training in Cloudina (error not present in Alvis)

### ISSUE THREAD

**Issue by Bergylta** [ocean-data-factory-sweden/koster_yolov4#441]
## 🐛 Bug
Error with MissingSchema when trying to create the Yaml-files after processing the annotations from Zooniverse using Cloudina, error is not present on Alvis, the notebook seems to be unable to save the processed frames of the classes.

## To Reproduce (REQUIRED)
Location of Output: /cache/album/cache/kso-user/bucket/tmp_dir/KSO_Paulina_data1/
test proportion: 0,2
Input:
```
# Run the preparation script
mlp.prepare_dataset(
    agg_df=pp.aggregated_zoo_classifications,
    out_path=output_folder.selected,
    img_size=(720, 540),
    perc_test=percentage_test.value,
    out_format="yolo",
    track_frames=True,
)
```

Output:
```
---------------------------------------------------------------------------
MissingSchema                             Traceback (most recent call last)
/cache/album/cache/kso-user/kso/kso_utils/project.py in on_button_clicked(b)
   1429                 self.species_of_interest = species_list.value
   1430                 # code for prepare dataset for machine learning
-> 1431                 self.modules["yolo_utils"].frame_aggregation(
   1432                     project=self.project,
   1433                     server_connection=self.server_connection,

/cache/album/cache/kso-user/kso/kso_utils/yolo_utils.py in frame_aggregation(project, server_connection, db_connection, out_path, perc_test, class_list, img_size, out_format, remove_nulls, track_frames, n_tracked_frames, agg_df)
    992                 if link_bool:
    993                     image_output = PIL.Image.open(
--> 994                         requests.get(name[0], stream=True).raw
    995                     )
    996                 else:

/opt/tljh/user/lib/python3.10/site-packages/requests/api.py in get(url, params, **kwargs)
     71     """
     72 
---> 73     return request("get", url, params=params, **kwargs)
     74 
     75 

/opt/tljh/user/lib/python3.10/site-packages/requests/api.py in request(method, url, **kwargs)
     57     # cases, and look like a memory leak in others.
     58     with sessions.Session() as session:
---> 59         return session.request(method=method, url=url, **kwargs)
     60 
     61 

/opt/tljh/user/lib/python3.10/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    573             hooks=hooks,
    574         )
--> 575         prep = self.prepare_request(req)
    576 
    577         proxies = proxies or {}

/opt/tljh/user/lib/python3.10/site-packages/requests/sessions.py in prepare_request(self, request)
    482 
    483         p = PreparedRequest()
--> 484         p.prepare(
    485             method=request.method.upper(),
    486             url=request.url,

/opt/tljh/user/lib/python3.10/site-packages/requests/models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
    365 
    366         self.prepare_method(method)
--> 367         self.prepare_url(url, params)
    368         self.prepare_headers(headers)
    369         self.prepare_cookies(cookies)

/opt/tljh/user/lib/python3.10/site-packages/requests/models.py in prepare_url(self, url, params)
    436 
    437         if not scheme:
--> 438             raise MissingSchema(
    439                 f"Invalid URL {url!r}: No scheme supplied. "
    440                 f"Perhaps you meant https://{url}?"

MissingSchema: Invalid URL 'h': No scheme supplied. Perhaps you meant https://h?
```

## Expected behavior
Ideally the frames would be processed and then saved to the specified directory together with the train and valid.txt as well as the corresponding yaml-files used for the model training.

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

## Additional context
Could something have gone wrong when exporting from zooniverse i wonder

**Comment by Bergylta** [comment]
Bumping this up to prio 1 for now  @Diewertje11

**Comment by Diewertje11** [comment]
When trying to replicate this issue, we found out that this issue did not appear in an older version of the code. Cdn-admin had the code from commit 5fdb4d7 from 8 Augustus 2024. There the issue did not occur and it works as expected.
However, at current dev at commit ec0c202, this issue occurs like Emil described. I looked at what the difference was between these commits related to line 994 in yolo_utils.py, which is where the error message points to. This line was changed in commit 3ce6150 ([Fix missing species_id issue · ocean-data-factory-sweden/kso@3ce6150](https://github.com/ocean-data-factory-sweden/kso/commit/3ce6150ca3c6399e2e2355e03f28e783718149ed#diff-c3fcaf7c8df460374f60c55b7e4f1153ac4f9c3185ff3b4ccdbf19f380eca2daR555)) and it is unclear to me why this was change was made in the code. 
But it is also unclear to me why other parts of this same function (frame_aggregation) did already use name[0] instead of name before this commit. So it seemed like this was the only part where we use name instead of name[0]. So maybe that was the reason why it was changed?

However, if I change it back and revert that commit, so that we just use name instead of name[0], the bug disappears and the code runs. Since that solves the problem, I will commit that to dev, but with the risk of introducing new bugs somewhere else, since it is unclear to me why this code was changed in the first place.

With that fix, I will close this issue. If you run into any new problems, please let me know!
