### ISSUE TITLE
Add YOLOv8 Segmentation baseline model to wandb

### ISSUE THREAD

**Issue by Bergylta** [ocean-data-factory-sweden/koster_yolov4#450]
## 🚀 Feature

the mlp.registry = "wandb" lacks the yolov8 object segmentation baseline model, which would be a good thing to add

## Motivation

The lack of a option to train a segmentation model when mlflow is not working and we have to use the wandb is a bit of a roadblock for when segmentation models are requested by users, thus I think it would be good to be able to add this baseline model to the wandb registry as well.

https://docs.wandb.ai/guides/integrations/ultralytics/

**Comment by Diewertje11** [comment]
Hej!
I added the model to the WandB registry.  It is called yolov8m-seg-base-model. 
This is the same segmentation baseline model that you got when the registry was set to MLflow in the code. However, this was not because the model was actually present in MLflow, but we downloaded it directly from Ultralytics every time we ran it. 
But now it is in the WandB registry: https://wandb.ai/koster/model-registry/artifacts/model/yolov8m-seg-base-model/v0

So with that I think that this issue is solved. However, I create a new issue for if we want to continue working with WandB in the future, since the model registry is not easily accessible via the webinterface. I think because the name of the team has changed at some point. So see issue #453.
